export const GET_LIST_COLLECTION_ACTION = 'GET_LIST_COLLECTION_ACTION';
export const GET_LIST_COLLECTION_SUCCESS_ACTION = 'GET_LIST_COLLECTION_SUCCESS_ACTION';
export const GET_LIST_COLLECTION_FAILURE_ACTION = 'GET_LIST_COLLECTION_FAILURE_ACTION';

export const GET_LIST_ITEM_COLLECTION_ACTION = 'GET_LIST_ITEM_COLLECTION_ACTION';
export const GET_LIST_ITEM_COLLECTION_SUCCESS_ACTION = 'GET_LIST_ITEM_COLLECTION_SUCCESS_ACTION';
export const GET_LIST_ITEM_COLLECTION_FAILURE_ACTION = 'GET_LIST_ITEM_COLLECTION_FAILURE_ACTION';

export const ADD_NEW_LIST_ITEM_COLLECTION_ACTION = 'ADD_NEW_LIST_ITEM_COLLECTION_ACTION';
export const ADD_NEW_ITEM_COLLECTION_SUCCESS_ACTION = 'ADD_NEW_ITEM_COLLECTION_SUCCESS_ACTION';
export const ADD_NEW_ITEM_COLLECTION_FAILURE_ACTION = 'ADD_NEW_ITEM_COLLECTION_FAILURE_ACTION';