export const list = [
    {title: "title 0", description: "description0", status: "OPEN", owner: null, list: 1},
    {title: "title 1", description: "description1", status: "OPEN", owner: null, list: 2},
    {title: "title 2", description: "description2", status: "OPEN", owner: null, list: 3},
    {title: "title 3", description: "description3", status: "OPEN", owner: null, list: 1},
    {title: "title 4", description: "description4", status: "OPEN", owner: null, list: 1},
    {title: "title 5", description: "description5", status: "OPEN", owner: null, list: 1},
    {title: "title 6", description: "description6", status: "OPEN", owner: null, list: 1},
    {title: "title 7", description: "description7", status: "OPEN", owner: null, list: 1},
    {title: "title 8", description: "description8", status: "OPEN", owner: null, list: 1},
    {title: "title 9", description: "description9", status: "OPEN", owner: null, list: 1},
    {title: "title 10", description: "description10", status: "OPEN", owner: null, list: 1},
    {title: "title 11", description: "description11", status: "OPEN", owner: null, list: 1},
    {title: "title 12", description: "description12", status: "OPEN", owner: null, list: 1},
    {title: "title 13", description: "description13", status: "OPEN", owner: null, list: 1},
    {title: "title 14", description: "description14", status: "OPEN", owner: null, list: 2},
    {title: "title 15", description: "description15", status: "OPEN", owner: null, list: 1},
    {title: "title 16", description: "description16", status: "OPEN", owner: null, list: 2},
    {title: "title 17", description: "description17", status: "OPEN", owner: null, list: 2},
    {title: "title 18", description: "description18", status: "OPEN", owner: null, list: 2},
    {title: "title 19", description: "description19", status: "OPEN", owner: null, list: 2},
    {title: "title 20", description: "description20", status: "OPEN", owner: null, list: 2},
    {title: "title 21", description: "description21", status: "OPEN", owner: null, list: 2},
    {title: "title 22", description: "description22", status: "OPEN", owner: null, list: 2},
    {title: "title 23", description: "description23", status: "OPEN", owner: null, list: 2},
    {title: "title 24", description: "description24", status: "OPEN", owner: null, list: 2},
    {title: "title 25", description: "description25", status: "OPEN", owner: null, list: 2},
    {title: "title 26", description: "description26", status: "OPEN", owner: null, list: 3},
    {title: "title 27", description: "description27", status: "OPEN", owner: null, list: 3},
    {title: "title 28", description: "description28", status: "OPEN", owner: null, list: 4},
    {title: "title 29", description: "description29", status: "OPEN", owner: null, list: null},
    {title: "title 30", description: "description30", status: "OPEN", owner: null, list: 4},
    {title: "title 31", description: "desciption31", status: "OPEN", owner: null, list: null},
    {title: "title 32", description: "desciption32", status: "OPEN", owner: null, list: 4},
    {title: "title 33", description: "description33", status: "OPEN", owner: null, list: null},
    {title: "title 34", description: "description34", status: "OPEN", owner: null, list: 4},
    {title: "title 35", description: "description35", status: "OPEN", owner: null, list: null},
    {title: "title 36", description: "description36", status: "OPEN", owner: null, list: 5},
    {title: "title 37", description: "description37", status: "OPEN", owner: null, list: 6},
    {title: "title 38", description: "description38", status: "OPEN", owner: null, list: null},
    {title: "title 39", description: "description39", status: "OPEN", owner: null, list: null},
    {title: "title 40", description: "description40", status: "OPEN", owner: null, list: null},
    {title: "title 41", description: "description41", status: "OPEN", owner: null, list: null},
    {title: "title 42", description: "description42", status: "OPEN", owner: null, list: null},
    {title: "title 43", description: "description43", status: "OPEN", owner: null, list: null},
    {title: "title 44", description: "description44", status: "OPEN", owner: null, list: null},
    {title: "title 45", description: "description45", status: "OPEN", owner: null, list: null},
    {title: "title 46", description: "description46", status: "OPEN", owner: null, list: null},
    {title: "title 47", description: "description47", status: "OPEN", owner: null, list: null},
    {title: "title 48", description: "description48", status: "OPEN", owner: null, list: null},
    {title: "title 49", description: "description49", status: "OPEN", owner: null, list: null},
    {title: "title 50", description: "description50", status: "OPEN", owner: null, list: null},
    {title: "title 51", description: "description51", status: "OPEN", owner: null, list: null},
    {title: "title 52", description: "description52", status: "OPEN", owner: null, list: null},
    {title: "title 53", description: "description53", status: "OPEN", owner: null, list: null},
    {title: "title 54", description: "description54", status: "OPEN", owner: null, list: null},
    {title: "title 55", description: "description55", status: "OPEN", owner: null, list: null},
    {title: "title 56", description: "description56", status: "OPEN", owner: null, list: null},
    {title: "title 57", description: "description57", status: "OPEN", owner: null, list: null},
    {title: "title 58", description: "description58", status: "OPEN", owner: null, list: null},
    {title: "title 59", description: "description59", status: "OPEN", owner: null, list: null},
    {title: "title 60", description: "description60", status: "OPEN", owner: null, list: 3},
    {title: "title 61", description: "description61", status: "OPEN", owner: null, list: 3},
    {title: "title 62", description: "description62", status: "OPEN", owner: null, list: 3},
    {title: "title 63", description: "description63", status: "OPEN", owner: null, list: 3},
    {title: "title 64", description: "description64", status: "OPEN", owner: null, list: 3},
    {title: "title 65", description: "description65", status: "OPEN", owner: null, list: 3},
    {title: "title 66", description: "description66", status: "OPEN", owner: null, list: 3},
    {title: "title 67", description: "description67", status: "OPEN", owner: null, list: 3},
    {title: "title 68", description: "description68", status: "OPEN", owner: null, list: 3},
    {title: "title 69", description: "description69", status: "OPEN", owner: null, list: 3},
    {title: "title 70", description: "description70", status: "OPEN", owner: null, list: 3},
    {title: "title 71", description: "description71", status: "OPEN", owner: null, list: 3},
    {title: "title 72", description: "descripton72", status: "OPEN", owner: null, list: 3},
    {title: "title 73", description: "description73", status: "OPEN", owner: null, list: 3},
    {title: "title 74", description: "description74", status: "OPEN", owner: null, list: 3},
    {title: "title 75", description: "description75", status: "OPEN", owner: null, list: 3},
    {title: "title 76", description: "description76", status: "OPEN", owner: null, list: 6},
    {title: "title 77", description: "description77", status: "OPEN", owner: null, list: 6},
    {title: "title 78", description: "description78", status: "OPEN", owner: null, list: 6},
    {title: "title 79", description: "description79", status: "OPEN", owner: null, list: 6},
    {title: "title 80", description: "description80", status: "OPEN", owner: null, list: 6},
    {title: "title 81", description: "description81", status: "OPEN", owner: null, list: 6},
    {title: "title 82", description: "description82", status: "OPEN", owner: null, list: 6},
    {title: "title 83", description: "description83", status: "OPEN", owner: null, list: 6},
    {title: "title 84", description: "description84", status: "OPEN", owner: null, list: 6},
    {title: "title 85", description: "description85", status: "OPEN", owner: null, list: 6},
    {title: "title 86", description: "description86", status: "OPEN", owner: null, list: 6},
    {title: "title 87", description: "description87", status: "OPEN", owner: null, list: 6},
    {title: "title 88", description: "description88", status: "OPEN", owner: null, list: 6},
    {title: "title 89", description: "description89", status: "OPEN", owner: null, list: 6},
    {title: "title 90", description: "description90", status: "OPEN", owner: null, list: 5},
    {title: "title 91", description: "description91", status: "OPEN", owner: null, list: 5},
    {title: "title 92", description: "description92", status: "OPEN", owner: null, list: 5},
    {title: "title 93", description: "description93", status: "OPEN", owner: null, list: 5},
    {title: "title 94", description: "description94", status: "OPEN", owner: null, list: 5},
    {title: "title 95", description: "description95", status: "OPEN", owner: null, list: 5},
    {title: "title 96", description: "description96", status: "OPEN", owner: null, list: 5},
    {title: "title 97", description: "description97", status: "OPEN", owner: null, list: 4},
    {title: "title 98", description: "description98", status: "OPEN", owner: null, list: 4},
    {title: "title 99", description: "description99", status: "OPEN", owner: null, list: 4}
];

export const lists = [
    {name: 'list1', uid: 1, assigned: 1},
    {name: 'list2', uid: 2, assigned: 1},
    {name: 'list3', uid: 3, assigned: 1},
    {name: 'list4', uid: 4, assigned: 2},
    {name: 'list6', uid: 5, assigned: 2},
    {name: 'list7', uid: 6, assigned: 2}
];